# 请勿手动编辑此行
version = "0.0.11"

[instance]
url = "127.0.0.1:8080"
secure = false

[localInstance]
# 使用 qemu 启动 wrapper-manager
# 此设置会覆盖 [instance] 配置
enable = false
# Windows 使用 WHPX，Linux 使用 KVM
# Windows 用户可执行 `Get-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform` 检查 WHPX 是否启用
# Linux 用户可执行 `sudo kvm-ok` 检查 KVM 是否可用
enableHardwareAcceleration = false
# Windows WHPX 可能需要将 hardwareAccelerator 设置为 `whpx,kernel-irqchip=off`，并将 cpuModel 设置为 `qemu64-v1`
hardwareAccelerator = ""
memorySize = "512M"
cpuModel = "Cascadelake-Server-v5"
showWindow = false
startArgs = "-host 0.0.0.0 -port 32767 -debug"

[region]
# 歌曲元数据语言，会影响歌曲标题、艺人等信息
# 简体中文: zh-Hans-CN，繁体中文(香港): zh-Hant-HK，繁体中文(台湾): zh-Hant-TW
# 英语(英国): en-GB，英语(美国): en-US，日语: ja，韩语: ko
language = "zh-Hant-HK"
# 当歌曲所在地区不存在所选语言时打印警告
languageNotExistWarning = true

[download]
# 通过代理请求 Apple Music，仅支持 http 和 https 协议
proxy = ""
# 同时下载的歌曲数量
parallelNum = 1
# 最大运行任务数量
maxRunningTasks = 128
# 指定下载时使用的 Apple CDN IP，用于提升下载速度
# 台湾: 17.253.117.201-17.253.117.203
# 香港: 17.253.85.201-17.253.85.206, 17.253.87.195, 17.253.87.196, 17.253.87.201, 17.253.87.203
# 日本: 17.253.69.200, 17.253.69.202, 17.253.75.201, 17.253.75.202
appleCDNIP = ""
# 启用后，如果指定编码不存在，程序会自动查找其他可用编码进行下载
codecAlternative = true
# 备选编码查找优先级
# 如果希望无损音频不可用时下载 AAC 有损音频，可将 "aac-legacy" 添加到此配置
codecPriority = ["alac", "ec3", "ac3", "aac"]
# 将 Atmos(ec-3/ac-3) 封装为 M4A，并写入歌曲元数据
atmosConventToM4a = true
# 如果歌曲完整性检查失败，则任务失败且不会保存该歌曲
# 由于源文件本身也可能损坏，请谨慎开启
# 更多说明: https://github.com/WorldObservationLog/AppleMusicDecrypt?tab=readme-ov-file#song-did-not-pass-the-integrity-check
failedSongNotPassIntegrityCheck = false
# 遵循 Python Format 语法 (https://docs.python.org/3/library/string.html#formatstrings)
# 将音频信息写入 songNameFormat 和 playlistSongNameFormat
# 仅支持 alac 编码
# 可用值: bit_depth, sample_rate, sample_rate_kHz, codec
# 此功能可能会降低检查已有歌曲的速度
# 示例:
# audioInfoFormat = " [{codec}][{bit_depth}bit][{sample_rate_kHz}kHz]"
# songNameFormat = "{disk}-{tracknum:02d} {title}{audio_info}"
# 使用 alac 编码下载时，文件名示例:
# 1-01 名もなき何もかも [ALAC][16bit][44.1kHz]
# 使用其他编码下载时，文件名示例:
# 1-01 名もなき何もかも
audioInfoFormat = ""
# 可用值:
# title, artist, album, album_artist, composer,
# genre, created, track, tracknum, disk,
# record_company, upc, isrc, copyright, codec, audio_info
# song_id, album_id, album_created, total_tracks, total_disks
songNameFormat = "{disk}-{tracknum:02d} {title}"
# 可用值:
# title, artist, album, album_artist, composer,
# genre, created, track, tracknum, disk, album_created
# record_company, upc, isrc, copyright, codec, album_id
# disk_total
dirPathFormat = "downloads/{album_artist}/{album}"
# 可用值:
# title, artist, album, album_artist, composer,
# genre, created, track, tracknum, disk,
# record_company, upc, isrc, copyright,
# playlistName, playlistCuratorName, codec
playlistDirPathFormat = "downloads/playlists/{playlistName}"
# 可用值:
# title, artist, album, album_artist, composer,
# genre, created, track, tracknum, disk,
# record_company, upc, isrc, copyright, audio_info
# playlistName, playlistCuratorName, playlistSongIndex, codec
# song_id, album_id, album_created, total_tracks, total_disks
playlistSongNameFormat = "{playlistSongIndex:02d}. {artist} - {title}"
# 保存歌词为 .lrc 文件
saveLyrics = true
# lrc 或 ttml
# TTML 格式歌词会保存为 .ttml 后缀
lyricsFormat = "lrc"
# 仅适用于 lrc 歌词
lyricsExtra = ["translation", "pronunciation"]
saveCover = true
coverFormat = "jpg"
coverSize = "5000x5000"
# 限制音频文件的最高采样率和最大位深，仅对 ALAC 编码有效
maxSampleRate = 192000
maxBitDepth = 24
# 歌曲下载成功后执行的命令，会传入 filename 参数
# 示例: "\"C:\\Program Files\\DAUM\\PotPlayer\\PotPlayerMini64.exe\" \"{filename}\""
# 请注意转义问题
afterDownloaded = ""
retryTime = 8
maxWaitTime = 30

[notification]
# 下载完成、出现错误或失败时发送 Server酱³ 通知
# 在 https://sc3.ft07.com/ 获取 sendkey，请妥善保管，不要公开
enable = false
serverChan3SendKey = ""
# Server酱³ 标签使用 "|" 分隔
tags = "AppleMusicDecrypt|下载通知"

[metadata]
# 要写入歌曲的元数据
# 可用值:
# title, artist, album, album_artist, composer,
# genre, created, track, tracknum, disk,
# record_company, upc, isrc, copyright,
# lyrics, cover, ratings(rtng), song_id, album_id, artist_id
embedMetadata = ["title", "artist", "album", "album_artist", "composer", "album_created",
    "genre", "created", "tracknum", "disk", "lyrics", "cover", "copyright",
    "record_company", "upc", "isrc", "rtng", "song_id", "album_id", "artist_id"]
